on:
  push:
    branches: [main, dev]  # Run on pushes made into the main branch
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the OS to run the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your repository's code

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project dependencies

      - name: Run tests
        run: |
          pytest
